In [ ]:
import numpy as np

A = np.array([
    [0.8, 0.6, 0],
    [np.sqrt(2)*0.3, -np.sqrt(2)*0.4, -np.sqrt(2)*0.5],
    [np.sqrt(2)*0.3, -np.sqrt(2)*0.4, np.sqrt(2)*0.5],
])

print((A.T @ A > 0))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
